language: minimal
service: docker
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.23.2
  global:
  - secure: NV143SmT2NcxY7hPngMlfe5tvQbHS0TQIWbwt4qYjtnXShcR5NFKfXMGiGqRFlm0u0PLEq/f2UHxf2sL3ni+RmMyH2bWO5TBkiQA+WpaCZ4oPN1Hwp5j/gp0LacJ51zg1EjdpqMew3GYqjenbJ67rbg+DsnFIr/t5h95oHfru52dGNAYjRsOdri7x+eoIMREbrFKlI7+rR8DIT5vcZh15aOBF0uafoATZK0lyTBFYgtn853aZbs1y+swVM9ErmMBfe5fQ++WNRBg0gsP3FIkG1lUzE8vI9AKQa6HLAVLorxQQS7upGhdEH/Wy2njVayXUdsDT61kX5GPUVEKWDzmc6IxB75q05SpxCWg5aAzwiQlDMtXhjuD3t26ddbbrJY/jeW1Zh+hWwy/hj4QhKmPo0HAVp25kMHwG+IU3fraPJbATjxxdCSl42OrRBQDgwXhnekS9rGBee7Hnj/hlFIerswRknPuttUDQJ90ph9jAPIKCJmW9ApLp7mBwXhYcR1F9DNGzKpC7GDgTTY001shRrF6zqXdoMEWJfwTujMZ/TT9omXBj6F0y2hieVs+6/VfunanUzpyRPo5qrL1Bm/x0jSsyKZVDmXHE+5S9osVIO5hX+DcXIHvd4vOxmlPCC7sNJuG/DBDRM5Eod+0kOyBbGVd6kAJdKm2VVWeTfTIlRo=
  - secure: MvAa/p4+NRAMl3L422ZPAP2FOafT47453F3yqnE8t2b+dHMt3XD4SGRw1gjjip+lhGjuyWkOoy9fVWrHAPapxdeZ5Fzikoy3E7f1DFG+rKKW7uKdeL4qOqTdIZbMNTZwaigKDXJ9g2FyzQ0ZQ7DNovTQ8DbEi1rG3wzBZZcG8Ln+uct5e0Lwa05rNTcXADGN4wjL25YStrWbTSb3jHMUv1ZztSlimtCeYq3WdmCv8a36By/W6yPZbBSZQMXrxqHLTdEyIC+C/pK2zlBnPjwmAAMfnD9sv0PeEfKEaFoGFD/i069OZlZq7iW03BUUIgwsvtAxHPZgfA7iCJP1cA9ij3q0Bjc044ZKSIRT1b5TN9diP56/kf8+raHS6rQB2wVCsOiu/UVIUB6Snxio0tq5HefGrKCSmZhaTKUWVTLIytoNZ0+sOviPtxkl7Jgoj/bTirqfW1H0/TslqOVBtWFJgq9qKoYXIO0HUGjhEUMe+7703mFhP5Jn+L/VR7NDWRYz/sdB48XSfLR2mV9HfH2yVMCp0RKpZhljSunBP0TATcgJuV04wIQOU8tPjuHJfOJGakrjPtP11X1cqNRkmVX4gCXTSqCUoUixuNzLuyq1bDdr4o7U+6Sbh4mgZoOf/SpqyEUPAr7TySJ4l/zTBMVwA7UAeXcfhfbNfxPRs/8NdI8=
before_install:
- sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname
  -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
install: 
after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker login
