language: minimal

service: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo mv docker-compose /usr/local/bin
  
install: 
  - docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel